# Generated by Django 3.1.2 on 2020-12-10 18:22

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0002_auto_20201210_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='first_channel', editable=False, populate_from='room'),
            preserve_default=False,
        ),
    ]
