# Generated by Django 3.1.2 on 2020-12-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0003_channel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagesinchannel',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='messagesinchannel',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='created_by',
            new_name='created',
        ),
    ]
