# Generated by Django 3.1.2 on 2020-12-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0004_auto_20201210_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagesinchannel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='messagesinchannel',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='admin',
            new_name='created_by',
        ),
    ]
