# Generated by Django 3.1.2 on 2020-12-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0005_auto_20201211_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesinchannel',
            name='message',
            field=models.TextField(),
        ),
    ]
