# Generated by Django 3.1.2 on 2020-12-12 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborate', '0006_auto_20201211_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='person_id',
        ),
        migrations.AddField(
            model_name='people',
            name='person',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
