# Generated by Django 3.1.2 on 2020-12-12 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborate', '0008_auto_20201212_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='people',
            unique_together={('room', 'person')},
        ),
    ]
