# Generated by Django 3.1.2 on 2020-12-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0010_auto_20201212_1140'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('name', 'room')},
        ),
    ]
