# Generated by Django 3.1.2 on 2020-12-14 13:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborate', '0013_auto_20201212_1935'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('title', 'created_by')},
        ),
    ]
