# Generated by Django 3.1.2 on 2020-12-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0015_auto_20201214_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagesinchannel',
            options={'ordering': ('created_at',)},
        ),
    ]
