# Generated by Django 3.1.2 on 2020-12-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0016_auto_20201216_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='is_admin',
            field=models.CharField(default='false', max_length=5),
        ),
    ]
