# Generated by Django 3.1.2 on 2020-12-22 21:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0018_auto_20201221_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesinchannel',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
