# Generated by Django 3.1.2 on 2021-01-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0021_auto_20201231_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesinchannel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='collaborate/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagesinchannel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
