# Generated by Django 3.1.2 on 2021-01-11 11:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0022_auto_20210110_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesinchannel',
            name='file',
        ),
        migrations.AlterField(
            model_name='messagesinchannel',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=3),
            preserve_default=False,
        ),
    ]
