# Generated by Django 3.1.2 on 2021-01-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0023_auto_20210111_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='setting',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
