# Generated by Django 3.1.2 on 2021-01-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0024_channel_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='setting',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=10),
        ),
    ]
