# Generated by Django 3.1.2 on 2021-01-18 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborate', '0025_auto_20210118_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChannelUsers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_channel_people', to='collaborate.channel')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('channel', 'person')},
            },
        ),
    ]
