# Generated by Django 3.1.2 on 2021-01-18 07:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborate', '0026_privatechannelusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivateChannelUsers',
            new_name='PrivateChannelUser',
        ),
    ]
